#!/bin/tcsh  -e
set restrictions = RestrictionsWithId.xlsx
set certs =  AdditionalPrograms.xlsx

echo "Restrictions:             export/$restrictions "
echo "Additional Cert Programs: export/$certs"

set department_dir = $1
set department = `basename $department_dir`

set user = $2
set host = $3

(/usr/bin/env python enhanceAips.py --thesis $department_dir/ExcelExport*.xlsx -r $department_dir/$restrictions --cover_page export/SeniorThesisCoverPage.pdf --add_certs $department_dir/$certs --aips $department_dir  -l INFO  > $department_dir/$department.tsv ) |& tee  $department_dir/enhancedAips.trace
/usr/bin/env python sortByStatus.py  --thesis $department_dir/ExcelExport*.xlsx --aips $department_dir

foreach f ($department_dir/DSpaceSimpleArchive/Approved $department_dir/DSpaceSimpleArchive/Cancelled $department_dir/DSpaceSimpleArchive/Submitted $department_dir/DSpaceSimpleArchive/Not-Submitted $department_dir/DSpaceSimpleArchive/Under-Review)
  if (-e $f) then
    echo -n "$f :"
    ls -d $f/*/submission* | wc -l
  endif
end

if -e $department_dir/Multi-Author then
  echo "*** this batch contains multi authors thesis, see $department_dir/Multi-Author "
endif

echo ""

echo "Tarring file ..."
(cd export; tar cfz $department.tgz ./$department)
