version: 2.1

jobs:
  build:
    parameters:
      python_version:
        type: string
        default: '3.8.3'
    working_directory: ~/dspace-python
    docker:
      - image: circleci/python:<< parameters.python_version >>-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          name: Restore the cache
          keys:
            - pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: 'Install package dependencies using pipenv'
          command: |
            sudo pip install pipenv
            if [[ $(python --version) =~ 2\.7\. ]]; then
              cp Pipfile.legacy Pipfile
              cp Pipfile.lock.legacy Pipfile.lock
            fi
            pipenv lock --pre
            pipenv install
      - save_cache:
          key: pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/venv

  lint:
    parameters:
      python_version:
        type: string
        default: '3.8.3'
    working_directory: ~/dspace-python
    docker:
      - image: circleci/python:<< parameters.python_version >>-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          name: Restore the cache
          keys:
            - pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: 'Install package dependencies using pipenv'
          command: |
            sudo pip install pipenv
            if [[ $(python --version) =~ 2\.7\. ]]; then
              cp Pipfile.legacy Pipfile
              cp Pipfile.lock.legacy Pipfile.lock
            fi
            pipenv lock --pre
            pipenv install
      - run:
          name: 'Lint the Python source files'
          command: |
            pipenv run black
      - save_cache:
          key: pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/venv

  doc:
    parameters:
      python_version:
        type: string
        default: '3.8.3'
    working_directory: ~/dspace-python
    docker:
      - image: circleci/python:<< parameters.python_version >>-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          name: Restore the cache
          keys:
            - pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: 'Install package dependencies using pipenv'
          command: |
            sudo pip install pipenv
            if [[ $(python --version) =~ 2\.7\. ]]; then
              cp Pipfile.legacy Pipfile
              cp Pipfile.lock.legacy Pipfile.lock
            fi
            pipenv lock --pre
            pipenv install
      - run:
          name: 'Generate the code documentation'
          command: |
            pipenv run sphinx-build -b html source build/html
      - save_cache:
          key: pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/venv
      - store_artifacts:
          path: ~/dspace-python/build/html

  test:
    parameters:
      python_version:
        type: string
        default: '3.8.3'
    working_directory: ~/dspace-python
    docker:
      - image: circleci/python:<< parameters.python_version >>-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          name: Restore the cache
          keys:
            - pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: 'Install package dependencies using pipenv'
          command: |
            sudo pip install pipenv
            if [[ $(python --version) =~ 2\.7\. ]]; then
              cp Pipfile.legacy Pipfile
              cp Pipfile.lock.legacy Pipfile.lock
            fi
            pipenv lock --pre
            pipenv install
      - run:
          name: 'Run the Python unit and module tests'
          command: |
            echo 'no op'
      - save_cache:
          key: pip-packages-<< parameters.python_version >>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/venv

workflows:
  build_lint_doc_test:
    jobs:
      - build:
          name: build-python3.8
          python_version: '3.8.3'
      - lint:
          name: lint-python3.8
          python_version: '3.8.3'
          requires:
            - build-python3.8
      - doc:
          name: doc-python3.8
          python_version: '3.8.3'
          requires:
            - build-python3.8
      - test:
          name: test-python3.8
          python_version: '3.8.3'
          requires:
            - lint-python3.8
      - build:
          name: build-python2.7
          python_version: '2.7.18'
      - lint:
          name: lint-python2.7
          python_version: '2.7.18'
          requires:
            - build-python2.7
      - doc:
          name: doc-python2.7
          python_version: '2.7.18'
          requires:
            - build-python2.7
      - test:
          name: test-python2.7
          python_version: '2.7.18'
          requires:
            - lint-python2.7
