#!/bin/tcsh
set SUBMITTER_EMAIL = no-reply@institution.edu
set THESIS_CENTRAL_DOC_ROOT = /dspace/www/thesis_central

# u+rwx g+rx o+r
umask 003
echo "Available directories:"
ls -t $THESIS_CENTRAL_DOC_ROOT | fgrep -v html  | more
echo -n "enter directory > "

set dept = $<

set dept_www = $THESIS_CENTRAL_DOC_ROOT/$dept
cd  dept_www
echo "cd " `pwd`

fgrep EEROR tc_export/enhancedAips.trace
fgrep WARNING tc_export/enhancedAips.trace

foreach dir (Approved/*)
  set name = `basename $dir`
  echo $name
  echo -n "enter collection handle (format: 88435/dsp01xxxxxxxxx) > "
  set hdl =  $<

  set trace = import-trace-$name.txt
  set map = import-map-$name.txt

  echo /dspace/bin/dspace import -a -c $hdl -e $SUBMITTER_EMAIL -m $map -s $dir -w  ">" $trace
  echo  -n "Do now ? [Y/N] "
  if ("Y" == $< ) then
    /dspace/bin/dspace import -a -c $hdl -e $SUBMITTER_EMAIL -m $map -s $dir -w >& $trace
    cat $trace
    egrep '^[0-9]'  $trace
    echo "--"
    echo "Trace: $dept_www/$trace"
    echo "Id-Map: $dept_www/$map"
    echo ""
  endif
end

echo  "Sending summary to  $SUBMITTER_EMAIL"
(echo "Department: $dept"; \
 echo "#Imported Submissions: `wc -l import-map-*.txt`";  \
 echo ""; \
 echo "see details at https://dataspace.princeton.edu/www/thesis_central/$dept"; \
 echo ""; \
 echo "List of imported submission packges: ";  \
 echo "submission_ID    DSpace-ID"; \
 cat import-map-*.txt; )  |  mutt -s "TC Import $dept "  -- $SUBMITTER_EMAIL

exit 0
