#!/bin/tcsh -e
set SCRATCH_DIR = /var/scratch
set THESIS_CENTRAL_DOC_ROOT = /dspace/www/thesis_central

ls -t $SCRATCH_DIR/thesis-central/*.tgz | more

echo -n "Enter path of tgz in /var/scratch > "
set dept =  $<

set dept = `basename $dept`
set dept = $dept:r
echo $dept

cd  $THESIS_CENTRAL_DOC_ROOT
mkdir -p $dept
set DEPT_DIR_PATH = $THESIS_CENTRAL_DOC_ROOT/$dept
cd $dept
echo "extracting $SCRATCH_DIR/thesis-central/$dept.tgz   into `pwd`"

tar xfz $SCRATCH_DIR/thesis-central/$dept.tgz
mv $dept tc_export
ln -s tc_export/$dept.tsv .
ln -s tc_export/Approved .

# Ensure that all directories can be opened
find . -type d -exec chmod o+rx {} \;

# Ensure that all files can be opened
find .  -type f -exec chmod o+r {} \;

# Remove read permission for all submission subdirectories
chmod o-rwx $DEPT_DIR_PATH/tc_export/**/submission_*/*
foreach f (`find $DEPT_DIR_PATH/tc_export -name submission_\* `)
  (cd $f; chmod o-r * ; chmod o+r contents L*.txt *.xml )
end

