#!/bin/tcsh  -e
set SCRATCH_DIR = /var/scratch
set THESIS_CENTRAL_DOC_ROOT = /dspace/www/thesis_central

ls -t $SCRATCH_DIR/thesis-central/*.tgz | more

echo -n "enter path of tgz in /scratch > "
set dept =  $<

set dept = `basename $dept`
set dept = $dept:r
echo $dept

cd  $THESIS_CENTRAL_DOC_ROOT
mkdir -p $dept
cd $dept
echo "extracting $SCRATCH_DIR/thesis-central/$dept.tgz   into `pwd`"

tar xfz $SCRATCH_DIR/thesis-central/$dept.tgz
mv $dept tc_export
ln -s tc_export/$dept.tsv .
ln -s tc_export/Approved .

# count ORIG*pdf files in Approved submissiom directories
echo -n "\n#Approved/*/submission_*/ORIG*.pdf " ; ls Approved/*/submission_*/ORIG*.pdf | wc -l
echo -n "\n#Multi-Author/Approved/*/submission_*/ORIG*.pdf " ; ls tc_export/Multi-Author/Approved/*/submission_*/ORIG*pdf | wc -l
echo ""

#make all directories rx
find . -type d -exec chmod o+rx {} \;

# make all files readable
find .  -type f -exec chmod o+r {} \;

# remove read permission in submission directories
# except for contents LICENSE.txt and xml files
chmod o-rwx tc_export/*/*//submission_*/*
foreach f (`find . -name submission_\* `)
  (cd $f; chmod o-r * ; chmod o+r contents L*.txt *.xml )
end
